import {EXAMPLE,words,suggestions,validSelection,start,rate,restore,replacePassage} from './model.mjs';
const $=id=>document.getElementById(id);let saved=null;try{saved=restore(localStorage.getItem('recall-fold.v1'));}catch{$('saving').textContent='Browser saving is unavailable. You can still practice.';}
let text=saved?.text||EXAMPLE,selected=saved?.selected||suggestions(text),session=null,picking=false; $('source').value=text;
let previous=null;const undoText=document.createElement('button');undoText.className='quiet';undoText.id='undo-text';undoText.textContent='Undo text replacement';undoText.hidden=true;$('text-panel').before(undoText);undoText.style.marginTop='24px';undoText.onclick=()=>{if(!previous)return;({text,selected}=previous);previous=null;session=null;picking=false;$('source').value=text;undoText.hidden=true;save();render();$('start').focus();};
function save(){try{localStorage.setItem('recall-fold.v1',JSON.stringify({text,selected}));$('saving').textContent='Your passage and word choices are saved in this browser.';}catch{$('saving').textContent='Could not save here. Keep a copy of your text.';}}
function render(){const passage=$('passage');passage.replaceChildren();let end=0;const current=session?.queue[0];for(const w of words(text)){passage.append(text.slice(end,w.start));if(picking){const b=document.createElement('button');b.className='word';b.textContent=w.text;b.setAttribute('aria-pressed',selected.includes(w.id));b.setAttribute('aria-label',`${w.text}, word ${w.id+1}`);b.onclick=()=>{selected=selected.includes(w.id)?selected.filter(x=>x!==w.id):validSelection(text,[...selected,w.id]);b.setAttribute('aria-pressed',selected.includes(w.id));save();update();};passage.append(b);}else if(w.id===current){const s=document.createElement('span');s.className=session.revealed?'answer':'fold';s.textContent=session.revealed?w.text:'•••';if(!session.revealed)s.setAttribute('aria-label','Hidden word');passage.append(s);}else passage.append(w.text);end=w.end;}passage.append(text.slice(end));update();}
function update(){const running=!!session?.queue.length,done=!!session&&!running;$('state').textContent=picking?`${selected.length} words chosen`:running?`${session.queue.length} left to recall`:done?'This round is complete':'Ready to fold';$('prompt').textContent=picking?'Tap words to include or remove them.':running?(session.revealed?'How did you do? Your choice guides the next word.':'Say the missing word to yourself, then reveal it.'):done?`${session.remembered.length} words marked remembered this session.`:selected.length?'Your chosen words will appear one at a time.':'Choose at least one word to practice.';$('pick').textContent=picking?'Done choosing':'Choose words';$('pick').hidden=running;$('start').hidden=running||picking;$('start').disabled=!selected.length;$('start').textContent=done?'Practice again':'Fold a word';$('reveal').hidden=!running||session.revealed;$('again').hidden=$('remember').hidden=!running||!session.revealed;$('finish').hidden=!running;}
$('pick').onclick=()=>{picking=!picking;session=null;render();};$('start').onclick=()=>{session=start(selected);render();$('reveal').focus();};$('reveal').onclick=()=>{session.revealed=true;render();$('remember').focus();};for(const [id,value] of [['again',false],['remember',true]])$(id).onclick=()=>{session=rate(session,value);render();(session.queue.length?$('reveal'):$('start')).focus();};$('finish').onclick=()=>{session=null;render();$('start').focus();};
function replace(next){const change=replacePassage({text,selected},next);if(!change){$('input-status').textContent='Add a passage with at least one word, up to 20,000 characters.';$('source').focus();return;}previous=change.previous;({text,selected}=change.current);undoText.hidden=false;session=null;picking=false;save();render();$('input-status').textContent='Passage ready. Choose different words whenever you like.';$('text-panel').open=false;$('start').focus();}
$('use').onclick=()=>replace($('source').value);$('example').onclick=()=>{$('source').value=EXAMPLE;replace(EXAMPLE);};render();
