import {EXAMPLE,words,suggestions,validSelection,start,rate,restore,replacePassage,practiceWindow} from './model.mjs';
const $=id=>document.getElementById(id);let saved=null;try{saved=restore(localStorage.getItem('recall-fold.v1'));}catch{$('saving').textContent='Browser saving is unavailable. You can still practice.';}
let text=saved?.text||EXAMPLE,selected=saved?.selected||suggestions(text),session=null,picking=false,showFull=false; $('source').value=text;
let previous=null;const undoText=document.createElement('button');undoText.className='quiet';undoText.id='undo-text';undoText.textContent='Undo text replacement';undoText.hidden=true;$('text-panel').before(undoText);undoText.style.marginTop='24px';undoText.onclick=()=>{if(!previous)return;({text,selected}=previous);previous=null;session=null;picking=false;$('source').value=text;undoText.hidden=true;save();render();$('start').focus();};
function save(){try{localStorage.setItem('recall-fold.v1',JSON.stringify({text,selected}));$('saving').textContent='';}catch{$('saving').textContent='Could not save here. Keep a copy of your text.';}}
function render(){const passage=$('passage');passage.replaceChildren();const current=session?.queue[0],running=current!==undefined,context=running?practiceWindow(text,current):{start:0,end:text.length},shortened=context.start>0||context.end<text.length,range=showFull?{start:0,end:text.length}:context;let end=range.start;if(range.start>0)passage.append('… ');for(const w of words(text).filter(w=>w.start>=range.start&&w.end<=range.end)){passage.append(text.slice(end,w.start));if(picking){const b=document.createElement('button');b.className='word';b.textContent=w.text;b.setAttribute('aria-pressed',selected.includes(w.id));b.setAttribute('aria-label',`${w.text}, word ${w.id+1}`);b.onclick=()=>{selected=selected.includes(w.id)?selected.filter(x=>x!==w.id):validSelection(text,[...selected,w.id]);b.setAttribute('aria-pressed',selected.includes(w.id));save();update();};passage.append(b);}else if(w.id===current){const s=document.createElement('span');s.className=session.revealed?'answer':'fold';s.textContent=session.revealed?w.text:'•••';if(!session.revealed)s.setAttribute('aria-label','Hidden word');passage.append(s);}else if(!running&&selected.includes(w.id)){const mark=document.createElement('mark');mark.className='chosen-word';mark.textContent=w.text;passage.append(mark);}else passage.append(w.text);end=w.end;}passage.append(text.slice(end,range.end));if(range.end<text.length)passage.append(' …');$('context').hidden=!running||!shortened;$('context').textContent=showFull?'Focus on this word':'Show whole passage';update();}
function update(){const running=!!session?.queue.length,done=!!session&&!running;$('state').textContent=picking?`${selected.length} words chosen`:running?`${session.queue.length} left to recall`:done?'Round complete':`${selected.length} words to practice`;$('prompt').textContent=picking?'Choose the words you want to remember.':running?(session.revealed?'Did you remember it?':'Say the missing word, then reveal it.'):done?`${session.remembered.length} words marked remembered this session.`:selected.length?'Read the highlighted words, then hide one.':'Choose at least one word to practice.';$('pick').textContent=picking?'Done choosing':'Choose words';$('pick').hidden=running;$('start').hidden=running||picking;$('start').disabled=!selected.length;$('start').textContent=done?'Practice again':'Hide a word';$('reveal').hidden=!running||session.revealed;$('again').hidden=$('remember').hidden=!running||!session.revealed;$('finish').hidden=!running;}
$('pick').onclick=()=>{picking=!picking;session=null;render();};$('context').onclick=()=>{showFull=!showFull;render();};$('start').onclick=()=>{showFull=false;session=start(selected);render();$('reveal').focus();};$('reveal').onclick=()=>{session.revealed=true;render();$('remember').focus();};for(const [id,value] of [['again',false],['remember',true]])$(id).onclick=()=>{session=rate(session,value);showFull=false;render();(session.queue.length?$('reveal'):$('start')).focus();};$('finish').onclick=()=>{session=null;render();$('start').focus();};
function replace(next){const change=replacePassage({text,selected},next);if(!change){$('input-status').textContent='Add a passage with at least one word, up to 20,000 characters.';$('source').focus();return;}previous=change.previous;({text,selected}=change.current);undoText.hidden=false;session=null;picking=false;save();render();$('input-status').textContent='Passage ready. Choose different words whenever you like.';$('text-panel').open=false;$('start').focus();}
$('use').onclick=()=>replace($('source').value);$('example').onclick=()=>{$('source').value=EXAMPLE;replace(EXAMPLE);};render();
